#ifndef INPUT_H
#define INPUT_H

#include <common.h>

#define INPUT_FREECAM_TOGGLE       (BTN_L3 | BTN_R3)
#define INPUT_DEBUG_HUD_TOGGLE     BTN_SELECT

#define INPUT_FREECAM_FORWARD      BTN_UP
#define INPUT_FREECAM_BACKWARD     BTN_DOWN
#define INPUT_FREECAM_STRAFE_LEFT  BTN_LEFT
#define INPUT_FREECAM_STRAFE_RIGHT BTN_RIGHT
#define INPUT_FREECAM_UP           BTN_R1
#define INPUT_FREECAM_DOWN         BTN_L1
#define INPUT_FREECAM_PITCH_UP     BTN_TRIANGLE
#define INPUT_FREECAM_PITCH_DOWN   BTN_CROSS
#define INPUT_FREECAM_YAW_LEFT     BTN_SQUARE
#define INPUT_FREECAM_YAW_RIGHT    BTN_CIRCLE
#define INPUT_FREECAM_CYCLE_SPEED  BTN_L2
#define INPUT_FREECAM_TOGGLE_HELP  BTN_R2

#define INPUT_SETTINGS_UP          BTN_UP
#define INPUT_SETTINGS_DOWN        BTN_DOWN
#define INPUT_SETTINGS_DEC         BTN_LEFT
#define INPUT_SETTINGS_INC         BTN_RIGHT
#define INPUT_SETTINGS_DEC_FAST    BTN_L1
#define INPUT_SETTINGS_INC_FAST    BTN_R1
#define INPUT_SETTINGS_CONFIRM     BTN_CROSS_one
#define INPUT_SETTINGS_BACK        BTN_TRIANGLE

void Input_Capture(void);
int  Input_IsHeld(int buttonMask);
int  Input_IsTapped(int buttonMask);

#endif
