#ifndef SETTINGS_H
#define SETTINGS_H

#include <common.h>

typedef enum SettingsField
{
	SETTINGS_RELIC_SAPPHIRE = 0,
	SETTINGS_RELIC_GOLD,
	SETTINGS_RELIC_PLATINUM,
	SETTINGS_CRYSTAL_TIME,
	SETTINGS_GHOST_TIME_1,
	SETTINGS_GHOST_TIME_2,
	SETTINGS_GHOST_CHARACTER_1,
	SETTINGS_GHOST_CHARACTER_2,
	SETTINGS_LAPS,
	SETTINGS_INTRO_CUTSCENE,
	SETTINGS_GHOST,
	SETTINGS_HIGH_LOD,
	SETTINGS_CTR_TOKEN,

	SETTINGS_FEATURE_FIRST,
	SETTINGS_FREECAM = SETTINGS_FEATURE_FIRST,
	SETTINGS_DEBUG_HUD,
	SETTINGS_RESERVES,
	SETTINGS_HOT_RELOAD,
	SETTINGS_HOST_SETTINGS,
	SETTINGS_MAX_STATS,
	SETTINGS_FEATURE_END,

	SETTINGS_MODE_FIRST = SETTINGS_FEATURE_END,
	SETTINGS_MODE_ARCADE = SETTINGS_MODE_FIRST,
	SETTINGS_MODE_RELIC_RACE,
	SETTINGS_MODE_TIME_TRIAL,
	SETTINGS_MODE_CRYSTAL_CHALLENGE,
	SETTINGS_MODE_CTR_TOKEN,
	SETTINGS_MODE_BOSS_RACE,
	SETTINGS_MODE_END,

	SETTINGS_BOSS_FIRST = SETTINGS_MODE_END,
	SETTINGS_BOSS_1 = SETTINGS_BOSS_FIRST,
	SETTINGS_BOSS_2,
	SETTINGS_BOSS_3,
	SETTINGS_BOSS_4,
	SETTINGS_BOSS_5,
	SETTINGS_BOSS_END,

	SETTINGS_BOSS_ITEM_PRESET_FIRST = SETTINGS_BOSS_END,
	SETTINGS_BOSS_ITEM_PRESET_1 = SETTINGS_BOSS_ITEM_PRESET_FIRST,
	SETTINGS_BOSS_ITEM_PRESET_2,
	SETTINGS_BOSS_ITEM_PRESET_3,
	SETTINGS_BOSS_ITEM_PRESET_4,
	SETTINGS_BOSS_ITEM_PRESET_5,
	SETTINGS_BOSS_ITEM_PRESET_END,

	SETTINGS_FIELD_COUNT = SETTINGS_BOSS_ITEM_PRESET_END
} SettingsField;

#define SETTINGS_RELIC_TIERS 3

void Settings_ApplyCodePatches(void);
void Settings_PollHost(void);
void Settings_Open(struct RectMenu* mainMenu);
int  Settings_IsOpen(void);
void Settings_Update(void);
int  Settings_GetRelicTime(int tier);
int  Settings_GetCrystalTime(void);
int  Settings_GetGhostTime(int slot);
int  Settings_IsAvailable(void);

#endif
