#ifndef SETTINGS_H
#define SETTINGS_H

#include <common.h>

typedef enum SettingsField
{
	SETTINGS_RELIC_SAPPHIRE = 0,
	SETTINGS_RELIC_GOLD,
	SETTINGS_RELIC_PLATINUM,
	SETTINGS_CRYSTAL_TIME,
	SETTINGS_LAPS,
	SETTINGS_INTRO_CUTSCENE,
	SETTINGS_GHOST,

	SETTINGS_FEATURE_FIRST,
	SETTINGS_FREECAM = SETTINGS_FEATURE_FIRST,
	SETTINGS_DEBUG_HUD,
	SETTINGS_RESERVES,
	SETTINGS_HOT_RELOAD,
	SETTINGS_HOST_SETTINGS,
	SETTINGS_FEATURE_END,

	SETTINGS_MODE_FIRST = SETTINGS_FEATURE_END,
	SETTINGS_MODE_ARCADE = SETTINGS_MODE_FIRST,
	SETTINGS_MODE_RELIC_RACE,
	SETTINGS_MODE_TIME_TRIAL,
	SETTINGS_MODE_CRYSTAL_CHALLENGE,
	SETTINGS_MODE_CTR_TOKEN,
	SETTINGS_MODE_BOSS_RACE,
	SETTINGS_MODE_END,

	SETTINGS_BOSS_FIRST = SETTINGS_MODE_END,
	SETTINGS_BOSS_RIPPER_ROO = SETTINGS_BOSS_FIRST,
	SETTINGS_BOSS_PAPU_PAPU,
	SETTINGS_BOSS_KOMODO_JOE,
	SETTINGS_BOSS_PINSTRIPE,
	SETTINGS_BOSS_NITROS_OXIDE,
	SETTINGS_BOSS_END,

	SETTINGS_FIELD_COUNT = SETTINGS_BOSS_END
} SettingsField;

#define SETTINGS_RELIC_TIERS 3

void Settings_ApplyCodePatches(void);
void Settings_PollHost(void);
void Settings_Open(struct RectMenu* mainMenu);
int  Settings_IsOpen(void);
void Settings_Update(void);
int  Settings_GetRelicTime(int tier);
int  Settings_GetCrystalTime(void);
int  Settings_IsAvailable(void);

#endif
