#ifndef SETTINGS_H
#define SETTINGS_H

#include <common.h>

typedef enum SettingsField
{
	// which modes the main menu offers
	SETTINGS_MODE_FIRST = 0,
	SETTINGS_MODE_ARCADE = SETTINGS_MODE_FIRST,
	SETTINGS_MODE_RELIC_RACE,
	SETTINGS_MODE_TIME_TRIAL,
	SETTINGS_MODE_CRYSTAL_CHALLENGE,
	SETTINGS_MODE_CTR_TOKEN,
	SETTINGS_MODE_BOSS_RACE,
	SETTINGS_MODE_END,

	// every race
	SETTINGS_LAPS = SETTINGS_MODE_END,

	// relic race
	SETTINGS_RELIC_SAPPHIRE,
	SETTINGS_RELIC_GOLD,
	SETTINGS_RELIC_PLATINUM,

	// crystal race
	SETTINGS_CRYSTAL_TIME,

	// ctr token
	SETTINGS_CTR_TOKEN,

	// time trial
	SETTINGS_GHOST,
	SETTINGS_GHOST_TIME_1,
	SETTINGS_GHOST_CHARACTER_1,
	SETTINGS_GHOST_TIME_2,
	SETTINGS_GHOST_CHARACTER_2,

	// boss race, one block of SETTINGS_BOSS_ROW_COUNT rows per slot
	SETTINGS_BOSS_FIRST,
	SETTINGS_BOSS_1_ENABLED = SETTINGS_BOSS_FIRST,
	SETTINGS_BOSS_1_CHARACTER,
	SETTINGS_BOSS_1_ITEM_PRESET,

	SETTINGS_BOSS_2_ENABLED,
	SETTINGS_BOSS_2_CHARACTER,
	SETTINGS_BOSS_2_ITEM_PRESET,

	SETTINGS_BOSS_3_ENABLED,
	SETTINGS_BOSS_3_CHARACTER,
	SETTINGS_BOSS_3_ITEM_PRESET,

	SETTINGS_BOSS_4_ENABLED,
	SETTINGS_BOSS_4_CHARACTER,
	SETTINGS_BOSS_4_ITEM_PRESET,

	SETTINGS_BOSS_5_ENABLED,
	SETTINGS_BOSS_5_CHARACTER,
	SETTINGS_BOSS_5_ITEM_PRESET,
	SETTINGS_BOSS_END,

	// presentation
	SETTINGS_INTRO_CUTSCENE = SETTINGS_BOSS_END,
	SETTINGS_HIGH_LOD_TRACKS,
	SETTINGS_HIGH_LOD_CHARACTERS,

	// authoring tools
	SETTINGS_FEATURE_FIRST,
	SETTINGS_FREECAM = SETTINGS_FEATURE_FIRST,
	SETTINGS_DEBUG_HUD,
	SETTINGS_RESERVES,
	SETTINGS_HOT_RELOAD,
	SETTINGS_HOST_SETTINGS,
	SETTINGS_MAX_STATS,
	SETTINGS_FEATURE_END,

	SETTINGS_FIELD_COUNT = SETTINGS_FEATURE_END
} SettingsField;

// each boss slot contributes these rows, in this order
typedef enum SettingsBossRow
{
	SETTINGS_BOSS_ROW_ENABLED = 0,
	SETTINGS_BOSS_ROW_CHARACTER,
	SETTINGS_BOSS_ROW_ITEM_PRESET,
	SETTINGS_BOSS_ROW_COUNT,
} SettingsBossRow;

#define SETTINGS_RELIC_TIERS 3

void Settings_ApplyCodePatches(void);
void Settings_PollHost(void);
void Settings_Open(struct RectMenu* mainMenu);
int  Settings_IsOpen(void);
void Settings_Update(void);
int  Settings_GetRelicTime(int tier);
int  Settings_GetCrystalTime(void);
int  Settings_GetGhostTime(int slot);
int  Settings_IsAvailable(void);

#endif
